### ISSUE TITLE
Unable to connect to board

### ISSUE THREAD

**Issue by jevers76** [gepd/uPiotMicroPythonTool#1]
Windows 8.1
Sparkfun ESP32 Thing

I installed uPiot to Sublime 3.  When I issue any of the commands that would talk to the board through the serial port I get a dialog box to select which COM port to use, but when I select the port my ESP32 is connected to the port select window closes with no apparent communications.  I have tried open console, erase flash, download firmware, etc. I have tried two different boards one with Micropython already programmed and one erased. I have been able to use uPyCraft successfully so the boards and COM port are OK.

**Comment by gepd** [comment]
Can you please check the output of the Sublime Text console `ST Menu > View > Show Console`, after try to open the console or any other command it should show any possible error. Paste the output here so I can help you

**Comment by jevers76** [comment]
The last two lines 'reloading settings
Packages/User/upiot.sublime-settings' were the result of an open console
and a select serial port commands.

DPI scale: 1.25
startup, version: 3143 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/john/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/john/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/john/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.124431
startup time: 0.140431
first paint time: 0.140431
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.50-requests
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin uPIOT MicroPython Tool.upiot
plugins loaded
Package Control: No updated packages
reloading settings Packages/User/upiot.sublime-settings
reloading settings Packages/User/upiot.sublime-settings

**Comment by gepd** [comment]
Now I've realized; after you select the port no new window is open? It should create a new one with the console, I'll try the plugin at windows 8, can you confirm the Sublime Text version you have installed?

**Comment by jevers76** [comment]
What type of window should I open?  I can try tonight.  I downloaded and
installed 64 bit Sublime yesterday with the most recent version.  I first
un-installed an old install and deleted some sublime directores in
user\appData\.

**Comment by gepd** [comment]
I've installed Windows 8.1 and this is how it looks like:

![console_w8](https://user-images.githubusercontent.com/7091609/32285256-88ffe540-bf08-11e7-86ce-a8295c95e284.gif)

So I think the problem may be with the board (it's weird because ampy is from adafruit too), as I don't have one to debug it, can you try ampy in the board?

The are the steps to install it and test it:

* Install it with `pip install adafruit-ampy`
* List the file in your device with `ampy -p yourport ls`

Let me know if that command work with your board

**Comment by jevers76** [comment]
I tried ampy a few weeks ago just  and it seemed to work.  One difference I
see from your example above is as soon as you type open yours has COM3
already selected.  My computer was two COM ports and I am prompted to
select one.  When I make the selection the selection box closes and then
nothing.   I will try ampy again just to be sure.  I am guessing it is
unable to open the port I have selected.  I was planning to put some prints
in the sampy code.  Do you know if the print results will come out the
sublime consode?   What time zone are you in?  I am gmt -6 Minnesota, USA

**Comment by gepd** [comment]
The problem was there; if the plugin detect only one device, it will automatically select it and open the console if you have more than one devices it will make you select a port, but if you already have selected one and it's available it will select that port. To choose a new one, you should use the option `UPIOT: Select Serial Port` and then open the console.

There was a bug when multiples devices were connected. I've already fixed and you should get the update the next time you use ST, I still don't add a warning to restart Sublime after update the plugin, but you should do it to note the new changes.

I'm GMT-3 Santiago, Chile

Let me know if the problem is fixed or you find a new one, I'll happy to help you

**Comment by jevers76** [comment]
Hi, I am able to connect to my ESP32 board after I updated your new files.

Here are some observations and questions.  Please excuse me if some of my
questions are stupis as I am just starting with Micropython ans ESP32 and
Sublime.

1.  Is there a good way to update your changes?   I un-installed and
re-installed upiot.  Could I just overlay the new files on top of the old?
2. Is there a way to connect to the ESP where every key goes to the ESP.
Right now many keys seem to be filtered out like ctrl-C and other control
keys.
3. when I did 'sampy ls' it showed my files, but when I did 'sampy run
myfile.py' it showed file not found
4.  The run command 'UPIOT:Run Current File' did not seem to work,  but I
think it did work one time, i think
5. It would be nice to have a stop program command,  perhaps the ctrl-C
functioning would satisfy that.
6.  It would be nice to show the COM port connection status somewhere.

I only was able to spend a short time today, but I will in the near
future.  I was planning to merge ampy with the terminal example that is
with pyserial snd build my own ide, but now I will use upiot.

Thank You
John

**Comment by gepd** [comment]
I'll move your las question to a new issue to make this more organized. see https://github.com/gepd/uPiotMicroPythonTool/issues/2
