### ISSUE TITLE
Feature Request: run selected code/current line

### ISSUE THREAD

**Issue by mickley** [gepd/uPiotMicroPythonTool#4]
Unless I'm mistaken, this is currently not possible.  The addition of this feature would make the plugin really awesome for developing.

**Comment by gepd** [comment]
Yes, it's not possible at this moment, but I'll add it to the list of new features

**Comment by gepd** [comment]
I've added this feature in alpha `v0.1.5`

Re-open this issue if you have a problem or a comment
